---
- hosts: targets
  tasks:
  - name: Copy python files
    copy:
      src: /home/ec2-user/source/Transporter/python
      dest: /home/greyjuicelab/source/Transporter/python
      owner: greyjuicelab
      group: greyjuicelab
    notify: "activate python script"
  - name: Change file ownership, group and permissions
    file:
      path: /home/greyjuicelab/source/Transporter/python/Transporter.py
      mode: '0755'
  - name: Copy system unit files for timer (cron)
    copy:
      src: /home/ec2-user/source/Transporter/deploy/gjl-transporter.timer
      dest: /etc/systemd/system/gjl-transporter.timer
      owner: root
      group: root
      mode: '0644'
  - name: Copy system service unit file
    copy:
      src: /home/ec2-user/source/Transporter/deploy/gjl-transporter.service
      dest: /etc/systemd/system/gjl-transporter.service
      owner: root
      group: root
      mode: '0644'
  - name: Systemd daemon-reload
    systemd:
      state: restarted
      daemon_reload: yes
      name: gjl-transporter.service
  handlers:
    - name: Create venv
      listen: activate python script
      command: python3 -mvenv /home/greyjuicelab/source/Transporter/python/.venv
    - name:
      listen: activate python script
      file:
        path: /home/greyjuicelab/source/Transporter/python/.venv
        state: directory
        recurse: yes
        owner: greyjuicelab
        group: greyjuicelab
    - name: Activate
      listen: activate python script
      shell: source .venv/bin/activate
      args:
        executable: /bin/bash
        chdir: /home/greyjuicelab/source/Transporter/python/
    - name: Install requirements
      listen: activate python script
      pip:
        requirements: /home/greyjuicelab/source/Transporter/python/requirements.txt
        virtualenv: /home/greyjuicelab/source/Transporter/python/.venv
